server.port=${PORT:8080}
spring.application.name=hackathon
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:hackathon
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

llm.provider  = gemini
llm.api-key   = ${GEMINI_API_KEY}
llm.model     = gemini-2.0-flash
llm.base-url  = https://generativelanguage.googleapis.com
spring.jpa.defer-datasource-initialization=true
